#! /bin/bash
## This file is to be executed from the root of the repo.

# Path on the destination server.
# BJC_PATH='/home/cs/bh/public_html/bjc/';
BJC_PATH="../bjc/";
# ACCOUNT='michael.ball@login.eecs.berkeley.edu';
ACCOUNT='michael@abbenay.cs.berkeley.edu';

echo 'Starting to copy files to Berkeley...';
# Use $1, but .travis.yml (and others) must call this script with the password as an argument!
# TODO try to use SSHPASS env variable.
echo "SSHPASSTEST: ${SSHPASSTEST}";
rsync -avhz --rsh="sshpass -p $1 ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" ./_berkeley/* ${ACCOUNT}:${BJC_PATH};
result=$?;
echo 'Syncing complete!';
exit $result;
