#! /bin/bash
## This file is to be executed from the root of the repo.

# Path on the destination server.
# BJC_PATH='/home/cs/bh/public_html/bjc/';
BJC_PATH="./";
# ACCOUNT='michael.ball@login.eecs.berkeley.edu';
ACCOUNT='michael@abbenay.cs.berkeley.edu';

echo 'Starting to copy files to Berkeley...';
# Use $1, but .travis.yml (and others) must call this script with the password as an argument!
# TODO try to use SSHPASS env variable.
rsync -avhz --progress ./_berkeley/* ${ACCOUNT}:${BJC_PATH} 2>sync.err;
result=$?;
echo 'Syncing complete!';
echo 'ERROR LOG';
cat sync.err;
exit $result;
