# This file only overwrites the nececessary changes from _config
# Use when building: --config _config.yml _congfig_2.yml
url: https://bjc.berkeley.edu
# Duplicated to ensure that these two always match for Berkeley.
production_url: https://bjc.berkeley.edu

destination: _berkeley